application: servercloud-sara
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: static/\1
  upload: static/(.*\.ttf)
- url: /static/admin
  static_dir: static/admin
  expiration: '0'
- url: /.*
  script: ServerCloud.wsgi.application


libraries:
- name: django
  version: 1.5
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"

builtins:
- django_wsgi: on

